name:               "Benjamin Tam"
description:        "Senior Developer <a href='https://twitter.com/Readify'>@Readify</a>"

url:                "//teamtam.net"
gravatar_hash:      "7350352430200c5e4bf31ef8599ada02"
twitter:            "benjamintam"
github:             "teamtam"
stackoverflow:      "teamtam"

disqus_shortname:   "teamtamblog"

background:         "/assets/images/bg.jpg"

paginate:           4
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:title/

markdown:           kramdown

nav:
  - name:           "Index"
    href:           "/index"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
